package org.fdroid.ui

import androidx.compose.ui.graphics.Color

// Chumian App Store - Liquid Glass Blue Theme
val primaryLight = Color(0xFF1A73E8)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD3E3FD)
val onPrimaryContainerLight = Color(0xFF001D36)
val secondaryLight = Color(0xFF545F71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD8E3F8)
val onSecondaryContainerLight = Color(0xFF111C2B)
val tertiaryLight = Color(0xFF6C5676)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF5DAFF)
val onTertiaryContainerLight = Color(0xFF261430)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF1F5FB)
val onBackgroundLight = Color(0xFF1A1C20)
val surfaceLight = Color(0xFFF1F5FB)
val onSurfaceLight = Color(0xFF1A1C20)
val surfaceVariantLight = Color(0xFFDFE2EB)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF73777F)
val outlineVariantLight = Color(0xFFC3C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3035)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFA3C9FF)
val surfaceDimLight = Color(0xFFD9DBE0)
val surfaceBrightLight = Color(0xFFF1F5FB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEBEEF5)
val surfaceContainerLight = Color(0xFFE5E9F0)
val surfaceContainerHighLight = Color(0xFFDFE3EA)
val surfaceContainerHighestLight = Color(0xFFD9DDE5)

// Glassmorphism colors (semi-transparent)
val glassSurfaceLight = Color(0xB3FFFFFF)
val glassSurfaceVariantLight = Color(0x80FFFFFF)
val glassBorderLight = Color(0x33FFFFFF)

val primaryDark = Color(0xFFA3C9FF)
val onPrimaryDark = Color(0xFF003258)
val primaryContainerDark = Color(0xFF00497D)
val onPrimaryContainerDark = Color(0xFFD3E3FD)
val secondaryDark = Color(0xFFBCC7DB)
val onSecondaryDark = Color(0xFF263141)
val secondaryContainerDark = Color(0xFF3C4858)
val onSecondaryContainerDark = Color(0xFFD8E3F8)
val tertiaryDark = Color(0xFFD9BEE3)
val onTertiaryDark = Color(0xFF3C2946)
val tertiaryContainerDark = Color(0xFF543F5E)
val onTertiaryContainerDark = Color(0xFFF5DAFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12151A)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF12151A)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFC3C6CF)
val outlineDark = Color(0xFF8D9199)
val outlineVariantDark = Color(0xFF43474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3035)
val inversePrimaryDark = Color(0xFF1A73E8)
val surfaceDimDark = Color(0xFF12151A)
val surfaceBrightDark = Color(0xFF383A3F)
val surfaceContainerLowestDark = Color(0xFF0D0F14)
val surfaceContainerLowDark = Color(0xFF1A1D22)
val surfaceContainerDark = Color(0xFF1E2126)
val surfaceContainerHighDark = Color(0xFF292B30)
val surfaceContainerHighestDark = Color(0xFF33363B)

// Glassmorphism dark colors
val glassSurfaceDark = Color(0x661A1D22)
val glassSurfaceVariantDark = Color(0x441A1D22)
val glassBorderDark = Color(0x22FFFFFF)
